//Generated file please do not edit
//
//
//generated by BuildConfig.sh
import Foundation

struct BuildConfig { 
  fileprivate init() {}
    static let API_HOST = URL(string:"https://www.beta.moviedb.io/api")!
    static let GMS_API_KEY = "AIeaSvBdVl-cTICSwYKrZ75SuvNw7bbMuDt1KG0"
}
