#!/bin/sh

#  BuildConfig.sh
#  MovieDB
#
#  Created by Shah on 6/27/18.
#  Copyright © 2018 shah. All rights reserved.

echo "//Generated file please do not edit"
printf "//\n//\n//generated by BuildConfig.sh\n"
printf "import Foundation\n\n"
echo "struct BuildConfig { "
echo "  fileprivate init() {}"
env |\
grep "buildConfig_" | \
sed "s/buildConfig_/    static let /" | \
sed -E 's/=(.*)/ = "\1"/' | \
sed -E 's/"http.*/URL(string:&)!/'
echo "}"
